{% set name = "technical" %}
{% set version = "1.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/technical-{{ version }}.tar.gz
  sha256: 23a28118d64119411d5f0a9fd910b60ce1e0736c3ee5438c08a59802bcddf7ad

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9
    - setuptools >=46.4.0
    - wheel
    - pip
  run:
    - python >=3.9
    - ta-lib
    - pandas

test:
  imports:
    - technical
    - technical.consensus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/freqtrade/technical
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Different indicators developed or collected for the Freqtrade
  description: |
    This is a collection of technical indicators collected or developed
    for Freqtrade as well as utilities such as timeframe resampling.
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - jan-janssen
