{% set name = "technical" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/technical-{{ version }}.tar.gz
  sha256: 4f518eb6c1467d41c00fc63bdf6d607e5f588935ef1dea0043bab41c2b33e701

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - arrow
    - pandas
    - python >=3.6
    - ta-lib

test:
  imports:
    - technical
    - technical.consensus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/freqtrade/technical
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Different indicators developed or collected for the Freqtrade
  description: |
    This is a collection of technical indicators collected or developed
    for Freqtrade as well as utilities such as timeframe resampling.
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - jan-janssen
