{% set name = "technical" %}
{% set version = "1.5.3" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/technical-{{ version }}.tar.gz
  sha256: ffda73a8dbf25a23eee429307f5ace4b3b4ad7ab8b6c515fa6b8193607c90092

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - ta-lib
    - pandas

test:
  imports:
    - technical
    - technical.consensus
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/freqtrade/technical
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Different indicators developed or collected for the Freqtrade
  description: |
    This is a collection of technical indicators collected or developed
    for Freqtrade as well as utilities such as timeframe resampling.
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - jan-janssen
